### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by sari-tech**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Adding a new file and it's link
## What did you learn from the changes you have made?
Determining relationships of multiple databases
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Initially customer_purchase and market_date_info relationship seemed like a many to many to me. But on closely looking at the attributes, it was slear to be a many to 1 relationship.
## How were these changes tested?
SQL lite db
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by sari-tech** [comment]
Attaching image here in case it isn't displayed properly in the md file
SQL_homework_1

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
Your diagram is missing important components (i.e. all options under a column), you may resubmit before the end of the day for review

**Review by amanda-ng518 — APPROVED** [review]
HW1: I just checked the file again, I believe there's a white layer covering the words, all good now, 8/8

**Review by amanda-ng518 — APPROVED** [review]
HW2:
Join Q1 optional "AS", good job
8/8

**Comment by sari-tech** [comment]
> HW1: I just checked the file again, I believe there's a white layer covering the words, all good now, 8/8

Thank you!

**Review by amanda-ng518 — APPROVED** [review]
HW3: well done! 8/8

**Pull request merged**
